# NOTE: The goal of this compose file is to show a possible use
# of the environment built and stored in AWS ECR

# This file requires the following env vars:
# - AWS_ECR_REPO_URL_MRMUSTARD: url where Docker image is stored in ECR
# - MRMUSTARD_ENV_VERSION: image tag used to select the version

# After setting the required environment variables and running:
#
# docker compose -f docker-compose.env.yml up -d
# docker exec -it mrmustard-${MRMUSTARD_ENV_VERSION} bash
#
# your selected environment will be ready to use


version: "3.9"
services:
  mr-mustard:
    tty: true # Keep container running as interactive shell
    image: ${AWS_ECR_REPO_URL_MRMUSTARD}:${MRMUSTARD_ENV_VERSION}
    container_name: mrmustard-${MRMUSTARD_ENV_VERSION}
    volumes:
    - ./:/mrmustard
