name: builds
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    env:
      HYPOTHESIS_PROFILE: ci
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.10']

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Build and install Mr Mustard
        run: |
          python -m pip install --no-cache-dir --upgrade pip
          poetry build
          pip install dist/mrmustard*.whl

      - name: Install only test dependencies
        run: poetry install --no-root --with dev

      - name: Run tests
        run: python -m pytest tests -p no:warnings --tb=native
